---
title: Bernardinum
timezone: Europe/Warsaw
collections:
  authors:
    title: Autorzy
    output: false
  portfolio:
    title: Portfolio
    output: false
    permalink: "/portfolio/:name"
  posts:
    title: Blog
    output: true
  shop_items:
    title: Sklep
    output: false
    permalink: "/sklep/:name"
  uploads:
    title: Uploads
    output: true
baseurl: 
url: https://www.bernardinum.com.pl
permalink: "/:title"
repository: bernardinum/bernardinum.github.io

plugins:
- jekyll-feed
- jekyll-paginate-v2
- jekyll-archives
- jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /blog/:title/

pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: 10
  permalink: /strona/:num/
  title: ":title - strona :num"
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2

jekyll-archives:
  enabled:
  - tags
  - categories
  layouts:
    tag: tag
    category: category
  permalinks:
    tag: "/tag/:name/"
    category: "/blog/kategoria/:name/"
feed:
  collections:
    posts:
      path: "/index.xml"
highlighter: rouge
